obj-y += ntp.o clocksource.o jiffies.o timer_list.o

# CKLEE_TIME
# obj-$(CONFIG_GENERIC_CLOCKEVENTS)		+= clockevents.o
# obj-$(CONFIG_GENERIC_CLOCKEVENTS)		+= tick-common.o
# obj-$(CONFIG_GENERIC_CLOCKEVENTS_BROADCAST)	+= tick-broadcast.o
# obj-$(CONFIG_TICK_ONESHOT)			+= tick-oneshot.o
# obj-$(CONFIG_TICK_ONESHOT)			+= tick-sched.o
# obj-$(CONFIG_TIMER_STATS)			+= timer_stats.o


obj-y		+= clockevents.o
obj-y		+= tick-common.o
#obj-y	+= tick-broadcast.o
obj-y			+= tick-oneshot.o
obj-y			+= tick-sched.o
#obj-y			+= timer_stats.o
